# Generated by Django 3.2.6 on 2021-08-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="distance_travelled",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="transport_type",
            field=models.CharField(
                choices=[
                    ("BIKE", "Bike"),
                    ("PUBL", "Public Transport"),
                    ("WALK", "Walk"),
                ],
                default="WALK",
                max_length=4,
            ),
        ),
    ]
