# Generated by Django 3.2.6 on 2021-08-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_rename_event_eventmodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventModel",
            new_name="Event",
        ),
    ]
